{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim ) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "pixelfed.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
{{- end }}
