{{- if and .Values.externalDatabase.enabled ( not .Values.externalDatabase.existingSecret ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pixelfed-database
data:
  host: {{ .Values.externalDatabase.host }}
  port: {{ .Values.externalDatabase.port }}
  database: {{ .Values.externalDatabase.database }}
  username: {{ .Values.externalDatabase.username }}
  password: {{ .Values.externalDatabase.password }}
{{- end }}
