{{- if not .Values.pixelfed.app.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pixelfed.fullname" . }}-app-key
data:
  {{ if .Values.pixelfed.app.key }}
  key: {{ .Values.pixelfed.app.key | b64enc }}
  {{- else }}
  key: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
{{- end }}
