{{- if and .Values.externalValkey.enabled (not .Values.externalValkey.existingSecret) (or .Values.externalValkey.existingSecretKeys.password .Values.externalValkey.existingSecretKeys.port .Values.externalValkey.existingSecretKeys.host ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pixelfed.fullname" . }}-valkey
data:
  {{- if not .Values.externalValkey.existingSecretKeys.host }}
  host: {{ .Values.externalValkey.host | b64enc }}
  {{- end }}
  {{- if not .Values.externalValkey.existingSecretKeys.port }}
  port: {{ .Values.externalValkey.port | quote | b64enc  }}
  {{- end }}
  {{- if not .Values.externalValkey.existingSecretKeys.password }}
  password: {{ .Values.externalValkey.password | b64enc  }}
  {{- end }}
{{- end }}
