{{- if not .Values.pixelfed.mail.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pixelfed.fullname" . }}-mail
data:
  host: {{ .Values.pixelfed.mail.host | b64enc }}
  port: {{ .Values.pixelfed.mail.port | quote | b64enc}}
  {{- if .Values.pixelfed.mail.username }}
  username: {{ .Values.pixelfed.mail.username | b64enc }}
  {{- end }}
  {{- if .Values.pixelfed.mail.password }}
  password: {{ .Values.pixelfed.mail.password | b64enc }}
  {{- end }}
{{- end }}
