{{- if not .Values.pixelfed.mail.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pixelfed-mail
data:
  host: {{ .Values.pixelfed.mail.host }}
  port: {{ .Values.pixelfed.mail.port }}
  username: {{ .Values.pixelfed.mail.username }}
  password: {{ .Values.pixelfed.mail.password }}
{{- end }}
