{{- if not .Values.pixelfed.mail.existingSecret }}
{{- $username := .Values.pixelfed.mail.username | required ".Values.pixelfed.mail.username is required" }}
{{- $password := .Values.pixelfed.mail.password | required ".Values.pixelfed.mail.password is required" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pixelfed.fullname" . }}-mail
data:
  host: {{ .Values.pixelfed.mail.host | b64enc }}
  port: {{ .Values.pixelfed.mail.port | quote | b64enc}}
  {{- if .Values.pixelfed.mail.username }}
  username: {{ $username | b64enc }}
  {{- end }}
  {{- if .Values.pixelfed.mail.password }}
  password: {{ $password | b64enc }}
  {{- end }}
{{- end }}
